version: 2
jobs:
  build:
    working_directory: /coco-elb-dns-registrator
    docker:
      - image: golang:1
    steps:
      - checkout
      - run:
          name: External dependencies
          command: |
            curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.18.0
            wget https://raw.githubusercontent.com/Financial-Times/upp-coding-standard/v1.0.0/golangci-config/.golangci.yml
      - run:
          name: Go build
          command: go build -mod=readonly -v
      - run:
          name: Run Linters
          command: golangci-lint run --config=.golangci.yml --new-from-rev=master
  docker_build:
    working_directory: /coco-elb-dns-registrator
    docker:
      - image: docker:18
    steps:
      - checkout
      - setup_docker_engine
      - run:
          name: Build Dockerfile
          command: docker build .
workflows:
  version: 2
  test-and-build-docker:
    jobs:
      - build
      - docker_build:
          requires:
            - build
