version: 2
jobs:
  build:
    working_directory: /go/src/github.com/Financial-Times/coco-elb-dns-registrator
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run:
          name: External dependencies
          command: |
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run:
          name: Download vendored dependencies
          command: dep ensure -v -vendor-only
      - run:
          name: Go build
          command: go build -v
  dockerfile:
    working_directory: /coco-elb-dns-registrator
    docker:
      - image: docker:18.03
    steps:
      - checkout
      - setup_docker_engine
      - run:
          name: Build Dockerfile
          command: docker build .
workflows:
  version: 2
  test-and-build-docker:
    jobs:
      - build
      - dockerfile:
          requires:
            - build
